#personal settings
#This is the config file of UltimateRPG Plugin
Ultimate:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/URPGDB
    username: root
    password: 1q2w3e4r
  language:
    # Options:
    # English
    # Chinese
    language: English





  #System settings
  #DO NOT CHANGE THIS VALUE
  firstTimeLoad: true
