#This is the config file of UltimateRPG Plugin
Ultimate:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/UltimateRPGPlugin?useunicode=true&CharacterEncoding=UTF-8&useSSL=false
    username: root
    password: 1q2w3e4r
