#personal settings
#This is the config file of UltimateRPG Plugin
Ultimate:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/URPGDB
    username: root
    password: 1q2w3e4r
  language:
    # Options:
    # English(Default)
    # Chinese(Under development)
    language: English
  filelocation:

  functions:
    register&Login: true
    GUI: true
    PersonalStorage: true




  #catch
  firstTimeLoad: true
